export const PlayTypes = [
  { value: "chance", label: "Chance" },
  { value: "collaborative", label: "Collaborative" },
  { value: "mystery", label: "Mystery" },
  { value: "party", label: "Party" },
  { value: "strategy", label: "Strategy" },
  { value: "trivia", label: "Trivia" },
  { value: "wordGames", label: "Word Games" },
  { value: "bluffing", label: "Bluffing" },
  { value: "cardGame", label: "Card Game" },
  { value: "CityOrCivilizationBuilding", label: "City or Civilization Building" },
  { value: "collectable", label: "Collectable" },
  { value: "deduction", label: "Deduction" },
  { value: "dungeonCrawler", label: "Dungeon Crawler" },
  { value: "dexterity", label: "Dexterity" },
  { value: "dice", label: "Dice" },
  { value: "economic", label: "Economic" },
  { value: "educational", label: "Educational"},
  { value: "engineBuilding", label: "Engine Building"},
  { value: "exploration", label: "Exploration" },
  { value: "farming", label: "Farming" },
  { value: "fighting", label: "Fighting" },
  { value: "gamebooks", label: "Gamebooks" },
  { value: "humourous", label: "Humourous" },
  { value: "legacy", label: "Legacy" },
  { value: "mathBased", label: "Math Based" },
  { value: "matureAdult", label: "Mature/Adult" },
  { value: "maze", label: "Maze" },
  { value: "memory", label: "Memory" },
  { value: "miniatureGames", label: "Miniature Games" },
  { value: "murderMystery", label: "Murder Mystery" },
  { value: "negotiation", label: "Negotiation" },
  { value: "oneVs.Many", label: "One Vs. Many" },
  { value: "puzzleGames", label: "Puzzle Games" },
  { value: "racing", label: "Racing" },
  { value: "realTime", label: "Real-Time" },
  { value: "rolePlaying", label: "Role-Playing" },
  { value: "sandbox", label: "Sandbox"},
  { value: "territorybuilding", label: "Territory Building"},
  { value: "timePeriod", label: "Time Period, Historic or Future"},
  { value: "travel", label: "Travel"},
  { value: "warGame", label: "War Games"}
];
